spring:
  dubbo:
    application:
      name: summer-provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      # 服务的端口号，之后的应用可以每个服务区分一下
      port: 20882
    service:
      loadbalance: leastactive
      timeout: 5000
      retries: 0
    server: true
    scan: com.summer.business